apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 4
  selector:
    matchLabels:
      key: mypod
  template:
    metadata:
      labels:
        key: mypod
    spec:
      containers:
        - name: mycontainer
          image: nginx
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysqlconfig
                  key: MYSQL_ROOT_PASSWORD
